#version 450

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

void main()
{
    ivec2 p = ivec2(gl_GlobalInvocationID.xy);

    if (p.x >= 64 || p.y >= 64)
        return;

    vec2 uv = vec2(p) / vec2(63.0);

    /*
     * Deliberately recognizable pattern:
     *
     * R = X coordinate
     * G = Y coordinate
     * B = constant
     * A = 1
     */
    imageStore(
        outputImage,
        p,
        vec4(uv.x, uv.y, 0.25, 1.0)
    );
}
